version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
        environment:
          RAILS_ENV: test
          TZ: "Asia/Tokyo"
      - image: tkuchiki/delayed-mysql
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: mr_messenger_test
          MYSQL_ROOT_HOST: "%"
    steps:
      - checkout
      - run:
          name: Configure Bundler to use Bundler 2
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler -N
      - run:
          name: Install gems
          command: |
            bundle config set path 'vendor/bundle'
            bundle install
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace
      - run: bundle exec rails test
  bundle_update_pr:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
        environment:
          RAILS_ENV: test
          TZ: "Asia/Tokyo"
    steps:
      - checkout
      - run:
          name: Configure Bundler to use Bundler 2
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler -N
      - run:
          name: Raise bundle update PR for master branch
          command: |
            gem install circleci-bundle-update-pr -N
            circleci-bundle-update-pr ${BUNDLE_UPDATE_GITHUB_USERNAME} ${BUNDLE_UPDATE_GITHUB_EMAIL} test-circleci-scheduled-workflows

workflows:
  version: 2
  build:
    jobs:
      - build
  bundle_update_pr:
    triggers:
      - schedule:
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *" # Every 5 mins
          filters:
            branches:
              only:
                - test-circleci-scheduled-workflows
    jobs:
      - bundle_update_pr
