# DB name is projectname_development, or _test/_production.

# <<: *default copies all the config details from default.
# In the following line(s), those are overwritten with env-specific details.

# Surround any Ruby code that needs to be evaluated and printed with <%= %>

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: '127.0.0.1'
  socket: /tmp/mysql.sock
  port: 3306

development:
  <<: *default
  database: mr_messenger_development

test:
  <<: *default
  database: mr_messenger_test

production:
  <<: *default
  database: mr_messenger_production
  username: <%= Rails.application.credentials.db_username %>
  password: <%= Rails.application.credentials.db_password %>
  host: <%= Rails.application.credentials.db_host %>