# DB name is projectname_development, or _test/_production.

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: '127.0.0.1'
  socket: /tmp/mysql.sock
  port: 3306

development:
  <<: *default
  database: mr_messenger_development

test:
  <<: *default
  database: mr_messenger_test

production:
  <<: *default
  database: mr_messenger_production